
import Page from '../PageLayout';



export const metadata = {
  title: 'Inregistreaza - te ',
  description: 'Generated by create next app',
  robots:'noindex, folow'
};

export default function RootLayout({ children }) {
  return (
    <>
      <Page>
        <div>{children}</div>
      </Page>
    </>
  );
  }
    

      

     
