// import './globals.css';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import InregistrareComponent from './inregistrareComponent';



export const metadata = {
  title: 'Inregistreaza - te ',
  description: 'Generated by create next app',
  robots:'noindex, folow'
};

export default function RootLayout({ children }) {
  return (<>
    <InregistrareComponent>{children}</InregistrareComponent>
  </>
    );
  }
    

      

     
